#!/usr/bin/env python3
import time as t
import skilstak.colors as c
import random as r
snake = '''

                 /\ /\         /\ /\         /\ /\              _______   
                 / / \ \       / / \ \       / / \ \             \   _  \  
                / /   \ \     / /   \ \     / /   \ \            /  /_\  \ 
                / /    \ \    / /    \ \    / /    \ \           
               / /     \ \   / /     \ \   / /     \ \           \  \_/   \ 
 ____________ / /       \ \ / /       \ \ / /       \ \___________\_____  /
/_____/_____/ \/         \/ \/         \/ \/         \/_____/_____/     \/ 

'''
print(c.clear)
while True:
    for count in range(4):
        for count in range(11):
            t.sleep(0.3)
            print(c.base3 + 'Badgers!!!!!!!!')
        for count in range(2):
            print(c.red + 'Muuuuusssh'+ c.base3 + 'rooooooom!')
            t.sleep(0.75)
    for count in range(1):
        print(c.clear)
        print(snake)
        t.sleep(0.5)
        print(c.green + 'Argh! A Snake!')
        t.sleep(1.5)
        print(c.green + 'A Snaaaaaake!!!')
        t.sleep(2)
        print(c.green + 'Ooooooh, its a Snaaaaake!')
        t.sleep(1.5)
        print(c.clear)
