#!/usr/bin/env python3
import time as t
import colors as c
import random as r
print(c.clear)
while True:
    for count in range(4):
        for count in range(11):
            t.sleep(0.4)
            print(c.base3 + 'Badgers!!!!!!!!')
        for count in range(2):
            t.sleep(0.75)
            print(c.red + 'Muuuuusssh'+ c.base3 + 'rooooooom!')
    for count in range(1):
        print(c.green + 'Argh! A Snake!')
        t.sleep(0.5)
        print(c.green + 'A Snaaaaaake!!!')
        t.sleep(0.3)
        print(c.green + 'Why does it have to be Snake?!?!')
