#!/usr/bin/env python3
import time as t   
import colors as c

sleep = 0.1
n = 0

while True:
    for n in range(2048):
        binform = c.clear + c.red + '{}: {:011b}' + c.reset
        print(binform.format(n,n))
        t.sleep(sleep)
