#!/usr/bin/env python3
import colors as c
import time as t
def live():
    print('Right, off you go then.'  + c.reset)
def die():
    print('Thou art cast into the Gorge of Eternal Peril.')
def prompt(question):
    print(question)
    answer = input(c.green + '> ' + c.red).lower()
    print(c.reset)
    return answer
print(c.clear + c.orange + '''Who would cross the bridge of Death
Must answer me these questions three
'Ere the other side he see.''')
t.sleep(2)
print(c.clear + c.reset)
name = prompt('What is your name?')
t.sleep(1)
quest = prompt('What is your quest?')
t.sleep(1)
if name in ['lancelot', 'galahad']:
    color = prompt('What is your favorite color?')
    if color in ['red','blue','green','orange','yellow','purple']:
        live()
    else:
        die()
elif name == 'robin':
    assyria = prompt('What is the capital of Assyria?')
    if assyria in ['assur','ashur']:
        live()
    else:
        die()
elif name == 'arther':
    swallow = prompt('What is the airspeed velocity of an unladen swallow?')
    if swallow == 'what do you mean? african or european?':
        print('''What? I don't know that... AHHHHHHHHHHHHHHHHHH!!!!!''')
    elif swallow == 'slighty faster than that of a laden swallow':
        live()
    elif swallow in ['24 mph','11 mps','24 miles per hour','11 meters per second']
        live()
    else:
        die()
else:
     question = prompt('What does your father smell like?')
     if question == 'elderberries':
        live()
     else:
        die()
