#!/usr/bin/env python3
import colors as c
import time as t
import random as r

print(c.clear)
print('''Welcome to the Magical Dice Rolling Machine. Type roll to roll the dice.''')
roll = input(c.green + '> ' + c.red)
dice = [
'
