#!/usr/bin/env python3
import time as t
import colors as c
print(c.clear)
print(c.green +  '''Mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm, 
multiplication tables.''' + c.reset)
t.sleep(2)
print(c.clear + c.yellow + 'Which number?')
number = input(c.red + '> ' + c.green)
print(c.yellow + 'Here are the multiplication tables for ' + number + '.')
for multiplier in range(1,13):
    print(multiplier, end = ' '
    print(multiplier + 'x' + number + '=' + multiplier * int(number)) 
