#!/usr/bin/env python3
import colors as c
import random
from utils import ask



which = ask("Would you like to take the 'fluffy unicorn' quiz, or the 'Eragon' quiz?")
if which == 'fluffy unicorn':
    import fluffy as quiz
else:
    import eragon as quiz



print(c.clear + quiz.intro)


while quiz.questions:
    question_function = random.choice(quiz.questions)
    if question_function():
        quiz.questions.remove(question_function)




