#!/usr/bin/env python3
import colors as c
import time as t
from utils import ask
score = 0

def yes():
    print('You are correct!!!')

def no():
    print('''I'm sorry, that is incorrect.''') 

print(c.clear + c.magenta + '''Welcome to the Pink Fluffy Unicorn quiz.
Let's test your knowledge to see what you've learned so far.
''')
t.sleep(2)

def q1(): 
    a1 = ask('What color are the unicorns?')
    if 'pink' in a1:
        yes()
        score += 1
        return True
    no()
    return False

def q2():
    a2 = ask('Where are they dancing?')
    if 'rainbows' in a2:
        yes()
        return True
        score += 1
    no()
    return False

def q3():
    a3 = ask('Please use one word to describe the texture of their maaaaagical fur.')
    if a3 == 'smiles':
        yes()
        return True
        score += 1
    no()
    return False
q1()
t.sleep(2)
q2()
t.sleep(2)
q3()
t.sleep(2)
print(c.green + 'Thank you for taking the Pink Fluffy Unicorn test. I hope you learned something.')
t.sleep(2)
print(c.red + 'Your score is ' + score + '.')
