#!/usr/bin/env python3
import colors as c
import random as r
import time as t
seconds = 1
while True:
    t.sleep(1)
    print(c.random_color() + str(seconds) + c.cyan() + ' seconds')
    seconds += 1

