#!/usr/bin/env python3
import colors as c
import time as t

sides = []


n = 0

sides.append('''1''')
sides.append('''2''')
sides.append('''3''')
sides.append('''4''')
sides.append('''5''')
sides.append('''6''')

import random as r

while True:
   side = r.choice(sides)
   print(c.clear + c.random_color() + side + c.reset)
   input()
