#!/usr/bin/env python3
import colors as c
import time as t
print(c.clear + '''Mmmmmmmmmmmm, multiplication tables.''')
t.sleep(3)
print(c.clear + 'Which Number?')
n = input(c.red + '> ' + c.green)
print(c.yellow + 'Table for {}'.format(n))
for multiplier in range(12,0,-1):
    answer = multiplier * int(n)
    print('{} X {} = {}'.format(n,multiplier,answer))
