#!/usr/bin/env python3
import colors as c

print(c.clear + c.orange + 'Do you like Pancakes?')
p = input(c.green + '> ' + c.red)
if p == 'yes':
    print(c.clear + c.blue + 'Do you like French Toast?')
    f = input(c.yellow + '> ' + c.blue) 
    if f == 'yes':
      print(c.clear + c.purple + 'Do you like Waffles?')
      w = input(c.purple + '> ' + c.orange)
      if w == 'yes':
          print(c.clear + c.green + 'I am glad that you do not dissagree with me')
      else:
           print(c.red + 'I do not agree with you. I must kill you now.')

    else:
        print(c.red + 'I do not agree with you. I must kill you now.')

else:
    print(c.red + 'I do not agree with you. I must kill you now.')
           
